### ISSUE TITLE
Sending Long SMS

### ISSUE THREAD

**Issue by yalomoush** [elibom/mokai#32]
Hi,

I tried to send a long message, but I got  ie.omk.smpp.message.InvalidParameterValueException: Message is too long exception.

**Comment by lizhi2013** [comment]
how to use http://localhost:9081/?to=855189701525&from=1877&text=%E4%BD%A0%E5%A5%BD
to send LONG sms

**Comment by lizhi2013** [comment]
I suggest put 160 this value to config file
